name: Push verification

on:
  push:
  workflow_dispatch:

jobs:
  verify_installation_job:
    name: Verify if we can istall Gems
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Try update bundle
        run: |
          bundle config unset deployment
          bundle install

      - name: Run All tests
        if: ${{ env.SHOULD_SKIP == 'false' }}
        run: |
          echo 'TODO: Run all tests'
          echo "SHOULD_SKIP=${{ env.SHOULD_SKIP }}"
