name: Pipeline

on: push

env:
  SHOULD_SKIP: 'false'

jobs:
  verify_installation_job:
    name: Update Gems
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Try update bundle
        if: ${{ env.SHOULD_SKIP == 'false' }}
        run: |
          bundle update
          git diff --name-only | grep Gemfile.lock && should_skip=false || should_skip=true
          echo "SHOULD_SKIP=$should_skip" >> $GITHUB_ENV
          echo "SHOULD_SKIP=$should_skip"

      - name: Run All tests
        if: ${{ env.SHOULD_SKIP == 'false' }}
        run: |
          echo 'Run all tests'
          echo "SHOULD_SKIP=${{ env.SHOULD_SKIP }}"

      - name: Push changes
        if: ${{ env.SHOULD_SKIP == 'false' }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Gemfile.lock
          git commit -m"Automatic update of Gemfile.lock"
          git push
