name: Pipeline

on: push

jobs:
  verify_installation_job:
    name: Update Gems
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Check if Gemfile.lock is synchronized with Gemfile
        id: gemfile_initial_state_check
        run: |
          bundle install
          git diff --name-only | grep Gemfile.lock && gemfile_is_initially_updated=false || gemfile_is_initially_updated=true
          echo "gemfile_is_initially_updated=$gemfile_is_initially_updated" >> $GITHUB_OUTPUT

      - name: Try update bundle
        id: gemfile_update_attempt
        if: ${{ steps.gemfile_initial_state_check.outputs.gemfile_is_initially_updated }}
        run: |
          bundle update
          git diff --name-only | grep Gemfile.lock && gemfile_got_updates=true || gemfile_got_updates=false
          echo "gemfile_got_updates=$gemfile_got_updates" >> $GITHUB_OUTPUT

      - name: Run All tests
        if: ${{ steps.gemfile_update_attempt.outputs.gemfile_got_updates }}
        run: echo 'Run all tests'

      - name: Push changes
        if: ${{ steps.gemfile_update_attempt.outputs.gemfile_got_updates }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Gemfile.lock
          git commit -m"Automatic update of Gemfile.lock"
          git push
