name: Pipeline

on: push

env:
  UPDATE_JOB_CONTINUE: true

jobs:
  verify_installation_job:
    name: Update Gems
    runs-on: macos-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3.5.2
      - name: Install bundle
        run: bundle install
      - name: Check if gemfile is up to date
        run: git diff --name-only Gemfile.lock && "UPDATE_JOB_CONTINUE=false" >> $GITHUB_ENV
      - name: Update bundler
        if: ${{ env.UPDATE_JOB_CONTINUE }}
        run: bundle update
      - name: Check if gemfile is changed by the job
        if: ${{ env.UPDATE_JOB_CONTINUE }}
        run: git diff --name-only Gemfile.lock || "UPDATE_JOB_CONTINUE=false" >> $GITHUB_ENV
      - name: push changes
        if: ${{ env.UPDATE_JOB_CONTINUE }}
        run: |
          git add Gemfile.lock
          git commit -m"Update Gemfile.lock"
          git push
