name: Challenge1

on: push

jobs:
  ubuntu_job:
    name: ubuntu_job
    runs-on: ubuntu-lates
    steps:
      - name:
        run: date

  windows_job:
    name: windows_job
    runs-on: windows-lates
    steps:
      - name: Print Date
        run: Get-Date

  macos_job:
    name: macos_job
    runs-on: macos-lates
    steps:
      - name: Print Date
        run: date

  summary_job:
    name: summary_job
    runs-on: macos-lates
    needs: [ubuntu_job, windows_job, macos_job]
    steps:
      - name: Print Final Date
        run: date